### PR TITLE
Python flask

### PR DESCRIPTION
**Pull request by songty**
django's bit too heavyweight, trying out flask instead

### CODE REVIEW

**Comment by botandrose** [comment]
Awesome, glad to have you on board, Tian! I've been very curious how a python solution might stack up.

**Comment by botandrose** [comment]
I see that you've removed the trailing Z from the timestamp _assertions_ (vs raw database input), which is causing other implementations to fail. Even though MySQL might not respect ISO8061 timezones, doesn't mean we, friendly citizens of the json API universe won't! So I'm afraid you must leave the test case intact, and ensure your code returns ISO8061-compliant UTC timestamps.

**Comment by botandrose** [comment]
@songty Briefly took a look at the test failure here, and I believe the issue is that `pip` is trying to install packages globally, which requires `sudo`. However, I don't think we want to install anything globally, wouldn't it be nice if there was effectively a `node_modules` directory, but for python? I'm pretty sure that's what a python _virtual environment_ is: http://docs.python-guide.org/en/latest/dev/virtualenvs/ . See if setting up one of those to install to in `bin/setup` does the trick.

**Comment by songty** [comment]
@botandrose I added the virtual env and now it is hanging after `Installing setuptools, pip, wheel...done.`

**Comment by botandrose** [comment]
You got the python dependency madness working. Good work!

I bet this is another example of #49. Try removing `silently` from the last line of `bin/setup`, the one that starts the server, and I bet there will be an error message.

**Comment by songty** [comment]
Looks like hackage is down at the moment. @botandrose can you hit the rebuild button when you get the chance?

**Comment by botandrose** [comment]
Looks like you've got your error message! Is `make python_flask` passing on your local machine?

**Comment by botandrose** [comment]
BTW, if it isn't clear, the test framework is pinging /api/test over and over again, waiting for a 200 so that it knows the server is up, and then it can begin the test suite.

**Comment by botandrose** [comment]
@songty Seems like you've been mostly struggling with Travis configuration, which isn't exactly the point of this project, so I've gone in and figured out the Travis config for you. If you check out my `python-flask` branch`, I've added two commits. The first one gets Travis happy, and the second causes the Python server to exit after receiving SIGINT, which was an undocumented requirement (added to the README).

If you want to cherry-pick those two commits, then do a rebase squash, I think this could be ready to look at merging.

**Comment by songty** [comment]
done! Thanks for the travis assist! :smile:

**Comment by botandrose** [comment]
Awesome, this is mergable!

But before I merge, how interested are you in feedback? Ultimately, python_flask is your playground, so as long as it's green, you can do whatever you want in it. But if you want I can give you feedback on design. Totally up to you.

**Comment by songty** [comment]
Feedback away! There's aways room for improvement.

**Comment by botandrose** [comment]
Indeed, that's what I love about programming. Two smells I noticed right away:

1. The `clients ` method is 25 lines long. Too big to fit into one's head. I'd suggest liberal usage of extract method or even extract method object so that this method tells a high level story.

2. Many of the variable names in that method are inscrutable, making it harder to read and understand. I personally avoid abbreviations when naming things, and generally count terseness in tokens, not characters. There are differing views on this, as always, though.

**Comment by botandrose** [comment]
s/method/function/g

Just learned that python differentiates between the two.

**Comment by songty** [comment]
@botandrose go for another pass?

**Comment by botandrose** [comment]
Wow, much better! Good work.

The only thing I'd say at this point is that the variable names `data`, `result`, and `d` are opaque and not intention-revealing. You could probably name every variable in every program `data`, and it wouldn't be inaccurate, but it doesn't communicate much to the reader.

This is def good enough to merge, though, IMO, so I will. Nice job, Tian!

**Pull request merged**
