### PR TITLE
Initial clojure liberator implementation of the hello world test case.

### PR DESCRIPTION
**Pull request by jkwatson**
This should implement the hello world test case. And, it does work.

However, I'm having an issue having the process respond to SIGINT correctly.  It responds fine, except when bin/setup is backgrounded (like it is in the test script).  Any help about why this might be happening would be greatly appreciated (I've now spent about 3 hours trying to track down the root cause of this, and I'm completely stumped).

NB: requires java 8 and the clojure leiningen tool to be installed.

### CODE REVIEW

**Comment by botandrose** [comment]
Awesome! Clojure is on my list of languages to investigate, so I'm excited to see where this goes. I'll get Travis set up for Clojure, and then we can go from there WRT SIGINT.

**Comment by botandrose** [comment]
@jkwatson I've got something working on https://github.com/botandrose/eboshi_api_shootout/tree/clojure_liberator_hello_world . Two new commits:

https://github.com/botandrose/eboshi_api_shootout/commit/7ef0e1a59942708868586d0dfee9ee5b47c7b05a adds the official `lein` script to the repo at `bin/lein`, and uses that for bootstrapping dependencies, so that it works on Travis, etc. However, I'm not too familiar with the Clojure toolchain. Does this seem this reasonable? Should we not include the `lein` bootstrap script in the repo?

https://github.com/botandrose/eboshi_api_shootout/commit/bd6dff216fb07e89680498c7f4e1e5f600609c07 is a hack. I tried to figure out what's going on with the server ignoring SIGINT when backgrounded, but didn't really get anywhere, either. Now, if the server is still running after one second after receiving SIGINT, we hit it with a SIGTERM. This is not ideal for a number of reasons, but it means we can at least get this impl going. Hopefully a real solution will be discovered and we can revert this commit. What do you think?

**Comment by jkwatson** [comment]
@botandrose I haven't a clue as to what the best way to go with the lein script.  I'm totally new to clojure, myself.  :)  As to the SIGINT issue, I guess we should do what works for now, and back-burner trying to figure out what's going on.  It's very strange; I don't think I've ever encountered anything like it.

**Comment by botandrose** [comment]
Ok sounds good. Go ahead and cherry-pick or merge those commits over to your branch, and I'll merge this PR.

I agree that the SIGINT issue is very strange. My current hypothesis is that its a bug in Clojure itself or Jetty. Let's try to reduce it down to the simplest possible reproduction, and see if any of the folks in those communities can shed any light.

**Comment by jkwatson** [comment]
cherry picked and build passed!

**Comment by botandrose** [comment]
:tada: 

I'm gonna split out a new issue from this, concerning the SIGINT ignoring bug.

**Pull request merged**
