### PR TITLE
Haskell Scotty: JWT auth

### PR DESCRIPTION
**Pull request by botandrose**
I'm going to spend a week curled up in my sock drawer with a tub of chunky monkey to recover from this mental trauma.

### CODE REVIEW

**Comment by BartMassey** [comment]
What was traumatic? It looks like you ended up with something pretty reasonable. What parts did you find difficult?

Don't store the cleartext password in the source, especially if you're going to put the source on Github. Only ever store the hash, and store it in a separate credential file that you do not commit. (For all implementations, not just `haskell_scotty`, but I haven't looked at the others.)

**Comment by botandrose** [comment]
Hey Bart, the hard part was the part of it that was in Haskell. ;)

Seriously, though, making any headway still feels a bit like pulling teeth. I think I understand maybe 85% of what I'm doing, which is actually pretty good, I think. But the remaining 15% is very perplexing. I think I'm mostly suffering from the inability to effectively debug compiler errors, and even the ones that I understand!

For example, I may encounter some type mismatch error, but (because Haskell, to my understanding) I cant just shove a `debugger` statement in there to poke around and try to figure out the correct conversion. Even amateur `puts`-style debugging doesn't appear to be an option, if I'm not in a monad. I've had some success by decomposing the offending function into tiny tiny functions with explicit type signatures, and then I can narrow down the issue get a little more focused, but not much. And to even get to that point, it requires refactoring code that is not green, which is usually a reckless idea. After some thought, I now suspect that this is a use-case for happy-path unit tests in Haskell, but I haven't tried that yet. WDYT?

I also still struggle with basic goals like how to convert one known value to another known value. For example, the `JWT` library eventually returns your payload as an `Aeson` `Text`-`Value` key-value pair. I've worked with `Aeson` enough now to feel pretty comfortable with it. However, just getting the `Int` out of the `Value` took me almost an hour of fruitless stabbing in the dark, ineffectual reading of the `Aeson` documentation and source (yikes), and ultimately cargo-culting something from the interwebs after all previous efforts failed. And even I knew it was an `Int` in there because I put it there myself! I feel like it really shouldn't be that hard. I'm not sure if `Aeson` documentation is insufficient, or my knowledge of Haskell. Probably both, but more of the latter.

Ultimately, though, I'm starting to come to the opinion that Haskell is just too damn hard for mere mortals. I'm going to stick with it through this project, at least, so maybe I'll be feeling a bit better about it near the end.

</sobstory>

**Comment by botandrose** [comment]
Agreed on removing the secret from source. I'll probably just expose it as a ENV variable.

**Comment by BartMassey** [comment]
I'm learning a lot about what is hard in Haskell.

A lot of it *is* that the Aeson documentation is not too good, honestly. The other hard part of it is that you really jumped in at the deep end with this project: normally we don't start with something that requires IO and DB access and weird libraries.

The biggest thing, though, is that you have an attitude of grinding through without help that will serve you well in some languages, but not Haskell. When you get bogged in something like this, bug me: I'll get online with you or come over and we can work through it together. Or just get on the Haskell IRC channel or something. This is a language where you are learning not just new syntax, but new ideas.

Let's try to find time soon to do a serious code review.

**Comment by botandrose** [comment]
That makes sense. Thanks for making yourself available, I really appreciate it! I'll spend the rest of the week writing more tests (since two impls have implemented them all), and then let's have a Haskell date before poker on Sunday?

**Comment by BartMassey** [comment]
Sounds good.

**Comment by botandrose** [comment]
@BartMassey Okay, asking for help! I've pushed the secret key up to the top-level, with the aim that I could then simply replace it with a IO monadic call to either an environment variable or an RNG. However, I've run into a wall with both approaches. I think my compiler errors are due to running the IO monad inside the ActionM monad, but I thought liftIO was supposed to take care of that?

**Comment by BartMassey** [comment]
Are you OK now? I'm guessing this is the problem we resolved last night... At any rate the branch seems to build OK up to warnings.

**Comment by botandrose** [comment]
Nope, still stuck. This is work I did this morning, after our enlightening marathon last night. I had hoped to get this branch to a mergable point, but having the secret key in source is not okay, I'm sure you'll agree. I could definitely bash my brain through this problem, but I'm trying to take your advice to ask for help before doing so. :)

**Comment by BartMassey** [comment]
You can only `liftIO` in `ActionM`, not `ScottyM`. The fix I have supplied is a kludge, but will work.

**Comment by BartMassey** [comment]
OH, by the way you'll have to set the environment variable before things start working again.

**Comment by BartMassey** [comment]
Redone. This is why we don't code at 3AM. You'll be much happier now.

**Comment by botandrose** [comment]
Nice! You know, I swear I had tried literally that EXACT code. I wish I had kept it around so I could diff it and figure out what I was missing.

**Pull request merged**
