### PR TITLE
Haskell scotty check fields

### PR DESCRIPTION
**Pull request by BartMassey**
Check the client record field names against the database field names at run time, to guard against schema mismatch.

### CODE REVIEW

**Comment by botandrose** [comment]
Travis failure is saying the fields don't match. Bug?

**Comment by BartMassey** [comment]
Without the API completely implemented, nor a test database, I have no reasonable way to test this code. Do you want to finish the API, or shall I?

That said, the error message I'm currently emitting is terrible. I'll fix it.

**Comment by botandrose** [comment]
Since this particular impl is primarily a learning tool for myself, I'd prefer to struggle through the initial implementations of each endpoint myself, then turn to you when I hit walls, if that arrangement is amenable to you. Speaking of, I've hit a wall with the `POST /api/clients` endpoint. Wanna take a look at it with me before/during/after poker?

Also, I don't think I'm understanding your issues with testing, let's go over that in person, too.

**Comment by botandrose** [comment]
This looks great, Bart! DB connection handling is greatly simplified. Good to learn about the `import Prelude hiding (zip)` trick, too. I don't really understand the rest of it, but we're green!

So, this is good to merge, except the commit history is a bit weird... I see merge commits, multiple versions of the same commit, etc. Can you `rebase -i` against current master to clean this up?

**Comment by BartMassey** [comment]
OK. I've used a new branch to avoid forcing this one.

**Comment by botandrose** [comment]
Roger that. But feel free to force push PR branches when they're about to be merged, since the branch will be dead after the merge, anyways.

**Pull request closed without merging**
