### PR TITLE
Haskell scotty result constructor

### PR DESCRIPTION
**Pull request by BartMassey**
Added a result constructor that really should be part of mysql-simple. Now you can easily transform rows from the database into Client records. You do not want to know how this works.

Also took this opportunity to define interfaces for all the modules, renaming a few things in the process to avoid unnecessary module qualifiers.

The cabal.config file got updated. I really don't think it should be checked in. If it is desired to hold versions for testing with Travis, keep it locally but don't try to maintain it cross platform.

### CODE REVIEW

**Comment by BartMassey** [comment]
Note that the remote Travis build has failed because cabal can't find the modules I used. I don't know what to do here, really.

**Comment by BartMassey** [comment]
Also note that the client constructor is only type checked at runtime. This is sort of the best that can be done anyway, but don't be fooled about there being static type safety here. Only the database knows what is in the database at compile time.

**Comment by botandrose** [comment]
Yowza! At some point I'm gonna sit down and try to wrap my brain around what's going on here. Its great that it did turn out to be possible.

Can't merge this until its green, though, of course. You think that removing `cabal.config` is the way to go here? If that's the solution, then lets do it.

**Comment by BartMassey** [comment]
I don't quite understand the use case for `cabal freeze` myself. It seems to me that the only way you would use it without `cabal sandbox` is in a situation where you wanted to notice that libraries had been accidentally updated in your build environment. In this situation, you probably don't want `cabal.config` checked into Git, as someone else might have a different standard build. But I don't know.

**Comment by botandrose** [comment]
:tada:

**Pull request merged**
