### PR TITLE
OO-ify node hapi

### PR DESCRIPTION
**Pull request by botandrose**
@mradamh Was poking around your `node_hapi` impl, and decided to try out the new ES6 class system. I ended up with this refactoring, which I'll leave up to you to merge or close. This is your impl, not mine!

Benefits:
* Lower-level details have been extracted out of the main "controller", which now only knows about http, some top-level serialization, and Client.
* Client is cohesive, reusable, and can now be unit tested.
* Only Client is coupled to knex now, so it'd be simpler to swap out a different db access layer in the future.

Demerits:
* More indirection.

What do you think?

### CODE REVIEW

**Comment by mradamh** [comment]
Heh.  Much like you have a distaste for JavaScript I have a distaste for OO.  I lament the introduction of the class keyword in ES6.  😛😉

The decoupling is a plus. I'm planning on doing more asweI move past one "type" and pull out common functions.  I'm just more likely to approach in a functional style vs. OO.

Aside:  you should look at bookshelfjs.  It's an OO ORM on top of knex.

**Comment by botandrose** [comment]
Ha, not too surprised. Paul was just telling me about how you and Phil were discussing the "death of OO" at lunch. Just out of curiosity, what is your background, language-wise? My love for OO comes from experiencing it through Ruby, which is about as pure of an OO fantasy world as one can get. I had been noticing a functional accent in your style. Do you have experience with FP languages?

**Comment by mradamh** [comment]
Way back when in college I wrote C for a bunch of classes, and a wee bit of Java, but I didn't take either all that seriously.  I did a little bit of maintenance on a couple of Coldfusion (oh god the horror) and C# webapps in a job out of college after that, but not full time by any means.  Took up JS about 1.5 years ago.  I had not really touched much code beyond  tutorials and that kind of thing for maybe 10 years before I started learning JS..

I think I picked up JS at at time where there is sort of a semi-functional renaissance in the JS community going on.  Most of the 'hotness' in JS is very functional in style and it resonates with me.  Decided to try learning Elixir because it builds on what I like about functional programming, but without going down a total rabbit hole (ala Haskell).

**Comment by botandrose** [comment]
Ah, interesting... thanks for sharing! I thought I had it bad with PHP in my early years. Coldfusion may possibly be worse!

I've been watching the growing functional influence on JS, and I think you're right, the language fights you less when hewing towards a functional style than an OO style. Although, that appears to be changing, with undeniably wonderful additions like the class syntax :stuck_out_tongue_winking_eye: 

Myself, I've been exploring OO, DDD, and TDD in Ruby for the last eight years or so, and really enjoying all the benefits those things can bring when they are done well and done together. It's been very interesting trying to bring the lessons I've learned there over to other languages that aren't so amenable to it. Like JS, for example!

Looking ahead, I'm interested in exploring the benefits that FP paradigms have to offer: immutability, no side-effects, composability, and also what strongly-typed languages have to offer: less tests, correctness. My goal is to bring those lessons back, and to better understand the tradeoffs. Haskell seems to be be about as far as one could possibly push all those things, and about as far away from Ruby as one can get, philosophically (Ruby: happiness, Haskell: provable correctness). Plus, I have access to a Haskell guru in Bart, so that made it an easy decision! I doubt I'll do serious professional development in Haskell, but who really knows.

Longer term, Elixir is very much on my radar because it appears to be a confluence of Ruby's expressiveness and FP's strengths, so I'm very interested in seeing where your Elixir impl goes, and in toying with it myself.

Anyways, this has been a fun and eye-opening project thus far. Thanks for participating in it!

**Comment by BartMassey** [comment]
> Haskell seems to be be about as far as one could possibly push all those things,

Ha ha no. Let's start with [Coq](https://coq.inria.fr/) or [AGDA](http://wiki.portal.chalmers.se/agda/pmwiki.php). Once you've mastered those, we can move on to the hardcore stuff.

**Comment by botandrose** [comment]
Hahaha oh man, I should've known the rabbit hole always goes deeper!

**Pull request closed without merging**
