### PR TITLE
added a type constraint on main; did some formatting for readability

### PR DESCRIPTION
**Pull request by BartMassey**
This is the same code, but a bit cleaner and safer.

### CODE REVIEW

**Comment by botandrose** [comment]
Trying to fully grok this refactoring... So we're declaring the `main` function to be (to utilize?) an IO monad, and that `main` is going to return (), or atom, which is Haskell's version of null.

I'm a bit confused by the dropping of the do notation. How would we declare additional scotty endpoints after this refactoring? Store the result of `scotty 6969` in a variable, and call additional actions on that?

**Comment by BartMassey** [comment]
Main is (always) an IO monad which doesn't produce any result. The confusing thing about monads is that they notionally have internal side-effects, but those side effects are "wrapped up" so that all that can escape is a return value. This "protects" the internal state from messing with external computations.

I haven't looked at Scotty yet, so I'm not sure how it handles multiple endpoints. Just a sec... Yeah, the reason your tutorial used do notation there is because the arguments aren't actually run in the IO monad, but in a special ScottyM monad: the inner "do" in your code is actually of a different type, and type inference is figuring that out. Sigh. Let me restyle things a bit and push again. Note that the eval operator '$' is read from right to left, so you'd need to actually give the results of the last expression in a monad label and so forth, eventually ending up with passing the whole thing to "scotty 6969" for execution.

**Comment by BartMassey** [comment]
Do not merge this. It is stale.

**Comment by BartMassey** [comment]
OK, I pushed something better.

**Pull request closed without merging**
