### PR TITLE
Hello world in kotlin, served by spark/jetty

### PR DESCRIPTION
**Pull request by jkwatson**
Uses maven for the build system, so that will need to be installed to make this work.

### CODE REVIEW

**Comment by botandrose** [comment]
Don't really understand the Travis failure message, other than it looks like a dependency issue. Do we need to install something on the Travis machine? How does one install kotlin?

**Comment by jkwatson** [comment]
I think what is needed is the java 8 jdk, rather than anything
kotlin-specific.

>

**Comment by botandrose** [comment]
Okay, great! That shouldn't be hard then. If there is an apt package for this, you can add it to the `addons.apt.packages` array in `.travis.yml`.

**Comment by jkwatson** [comment]
I'll take a look tonight or tomorrow.  I think openjdk8 should be available as an apt package.  Looks like maybe this?  sudo apt-get install openjdk-8-jdk

**Comment by botandrose** [comment]
I just tried it on my local machine and it appears to be correct, so it'll probably do the trick. :+1:

**Comment by jkwatson** [comment]
and, it's green!

**Comment by botandrose** [comment]
Great work!

**Comment by botandrose** [comment]
Prolly shoulda waited a rebase, looking at all dem commits. Oh well!

**Pull request merged**
