### PR TITLE
Implement GET /api/clients in Haskell Scotty (WIP)

### PR DESCRIPTION
**Pull request by botandrose**

### CODE REVIEW

**Comment by botandrose** [comment]
@BartMassey My first Haskell code! I'm starting to get a feel for the basics. Started with some pretty ugly code, and managed to refine it down to this. Before I try to introduce a db connection and pull some real data, what do you think? What changes would you make at this point?

**Comment by botandrose** [comment]
@BartMassey Hit a wall here, just trying to get a simple value out of mysql. I'm pretty sure I'm blocked on a lack of understanding monads. I can get an `IO String` out of mysql but I'm not sure how to turn that into a `String`. Reading through some documentation, I thought that `forM` and `mapM` are supposed to help cross what seems like the monad "bridge", but they're not doing the trick. I suspect my mental model   is not correct.

**Comment by BartMassey** [comment]
Yeah, the monad stuff is pretty confusing. The short answer is that you *can't* get the String out of an IO String: that restriction is there for your protection :-). Instead, you have to use the IO String inside an IO monad (or a monad that can work with one) and use the <- operator with the do notation to work with the String. Anyway, query_ returns a 64-bit integer, not a String in this context.

Not sure what happened to my old patches, but I've pushed a bunch of changes onto haskell_scotty for you to look at. The description of the big one should help explain what's going on.

The short answer is that I'm using pattern matching in fetchId to get the integer client id out, returning it wrapped in the IO monad, then using liftIO inside the clients action handler to get the thing wrapped in an ActionM monad instead of just IO; then <- can unwrap the integer for use in constructing the Client record for the JSON.

It gets easier, I promise. :-)

BTW, I also modified fetchId to hit a passworded test database. Be careful out there.

So I'm closing this pull request without merging it, I think, and just leaving my commits instead. Sorry my commits are such a mess. You can refactor them if it bothers you. At least they also brought the branch up to date with master.

**Comment by botandrose** [comment]
Thanks, Bart! I think this will get me moving again, or at least it'll give me something concrete to study as I try to wrap my brain around monads. My mental model is now that monads "infect" values. Once a value is infected by a monad, everything that consumes it downstream has to be monad-infected as well, which means everything that consumes them has to be monad-infected, and so on. Is this somewhat accurate? Reminds me of JavaScript async functions, which are viral in the same way. :fearful:

**Comment by BartMassey** [comment]
This is pretty accurate. You can extract a value from *some* monads (usually by a "run" function that executes the monadic code and returns the result). The IO monad is not one of them.

**Comment by botandrose** [comment]
Cool, I'm starting to get it. Just pushed a commit that changes the MySQL access credentials from file to environment variables, and I think I understand everything I've done! It's happening!!

**Comment by botandrose** [comment]
:tada: :neckbeard:

**Comment by botandrose** [comment]
Crap just realized this merge was premature... still tons of slime in the index action. Reverting.

**Pull request merged**
